sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12300.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12301.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12302.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12303.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12304.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12305.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12306.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12307.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12308.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12309.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12310.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12311.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12312.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12313.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12314.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12315.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12316.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12317.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12318.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12319.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12320.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12321.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12322.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12323.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12324.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12325.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12326.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12327.config &
sudo numactl --cpunodebind=0 --membind=0 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12328.config &
sudo numactl --cpunodebind=1 --membind=1 /home/Twitter/pelikan/_build/_bin/pelikan_slimcache config/slimcache-12329.config &
